---
fullname: Regexp Brzozowski
shortname: regexp-Brzozowski
opam_name: coq-regexp-brzozowski
organization: coq-community
community: true
action: true
coqdoc: false
doi: 10.1007/978-3-642-25379-9_11

synopsis: >-
  Decision procedures for regular expression equivalence in Coq
  using Mathematical Components

description: |-
  Coq library that formalizes decision procedures for regular
  expression equivalence, using the Mathematical Components
  library. The formalization builds on Brzozowski's derivatives
  of regular expressions for correctness.

publications:
- pub_url: https://link.springer.com/chapter/10.1007%2F978-3-642-25379-9_11
  pub_title: A Decision Procedure for Regular Expression Equivalence in Type Theory
  pub_doi: 10.1007/978-3-642-25379-9_11

authors:
- name: Thierry Coquand
  initial: true
- name: Vincent Siles
  initial: true

maintainers:
- name: Anton Trunov
  nickname: anton-trunov

opam-file-maintainer: palmskog@gmail.com

opam-file-version: dev

license:
  fullname: MIT License
  identifier: MIT

supported_coq_versions:
  text: 8.10 or later
  opam: '{(>= "8.10" & < "8.17~") | (= "dev")}'

dependencies:
- opam:
    name: coq-mathcomp-ssreflect
    version: '{(>= "1.12.0" & < "1.16~") | (= "dev")}'
  description: |-
    [MathComp](https://math-comp.github.io) 1.12.0 or later (`ssreflect` suffices)
- opam:
    name: coq-reglang
    version: '{(>= "1.1.3" & < "1.2~") | (= "dev")}'
  description: |-
    [RegLang](https://github.com/coq-community/reglang) 1.1.3 or later

tested_coq_opam_versions:
- version: 'coq-dev'
  repo: 'mathcomp/mathcomp-dev'
- version: '1.15.0-coq-8.16'
  repo: 'mathcomp/mathcomp'
- version: '1.15.0-coq-8.15'
  repo: 'mathcomp/mathcomp'
- version: '1.14.0-coq-8.14'
  repo: 'mathcomp/mathcomp'
- version: '1.13.0-coq-8.15'
  repo: 'mathcomp/mathcomp'
- version: '1.13.0-coq-8.14'
  repo: 'mathcomp/mathcomp'
- version: '1.13.0-coq-8.13'
  repo: 'mathcomp/mathcomp'
- version: '1.12.0-coq-8.12'
  repo: 'mathcomp/mathcomp'
- version: '1.12.0-coq-8.11'
  repo: 'mathcomp/mathcomp'
- version: '1.12.0-coq-8.10'
  repo: 'mathcomp/mathcomp'

ci_extra_dev: true

namespace: RegexpBrzozowski

keywords:
- name: regular expressions
- name: decision procedure
- name: relation algebra

categories:
- name: Computer Science/Decision Procedures and Certified Algorithms/Correctness proofs of algorithms
- name: Computer Science/Formal Languages Theory and Automata

documentation: |-
  ## Documentation

  The [paper](https://link.springer.com/chapter/10.1007%2F978-3-642-25379-9_11) on the
  formalization was written at Chalmers, in the ForMath Project. More information about
  the project and its achievements is available on the Chalmers website:
  - http://wiki.portal.chalmers.se/cse/pmwiki.php/ForMath
  - http://wiki.portal.chalmers.se/cse/pmwiki.php/ForMath/PapersAndSlides

  Overview of the Coq files:
  - `glue.v`: Basic definitions and lemmas.
  - `regexp.v`: Description and properties of regular expressions.
  - `gfinset.v`: Alternative definition of finite sets.
  - `finite_der.v`: The main proof that the set of derivatives of a regular
    expression is finite. The proof uses an abstract notion of similarity
    with the Brzozowski requirements.
  - `equiv.v`: Description of the equivalence procedure and proof of its correctness.
    In case of non-equivalence, we also produce a witness which is recognized by the
    first language but not by the second.
  - `sim1.v`: Naive implementation of similarity checking (by double inclusion), with
    only Brzozowski simplifications.
  - `sim2.v`: More efficient implementation of similarity checking (with a "compilation"
    of regular expressions) which implements many more simplifications.
  - `ex.v`: A few test cases which allow comparing the decision procedures in `sim1.v`
    and `sim2.v` inside Coq.
---
